sudo: false
cache:
  yarn: true
  directories:
  - node_modules
language: node_js
node_js:
- '8'

before_install:
- echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > ~/.npmrc
install:
- yarn install
- yarn run bootstrap
- yarn run flow:install

script:
- yarn run lint
- yarn run build
- yarn run test
- 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then yarn run deploy:canary; fi'

deploy:
  - provider: script
    skip_cleanup: true
    script: git remote set-url origin https://${GH_TOKEN}@github.com/scalecube/scalecube-js.git && git checkout develop && yarn run deploy:prepublish
    on:
      repo: scalecube/scalecube-js
      branch: develop
  - provider: script
    skip_cleanup: true
    script: git remote set-url origin https://${GH_TOKEN}@github.com/scalecube/scalecube-js.git && git checkout master && yarn run deploy:publish
    on:
      repo: scalecube/scalecube-js
      branch: master

after_deploy:
  - git status
