sudo: false
cache:
  yarn: true
  directories:
  - node_modules
language: node_js
node_js:
- '8'
before_install:
- echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > ~/.npmrc
install:
- yarn install
- yarn run bootstrap
- yarn run flow:install

before_script:
  - echo "before script"

script:
- yarn run build
- yarn run deploy:canary

deploy:
  matrix:
  - provider: script
    skip_cleanup: true
    script: yarn run deploy:prepublish
    on:
      repo: scalecube/scalecube-js
      branch: develop
  - provider: script
    skip_cleanup: true
    script: yarn run deploy:publish
    on:
      repo: scalecube/scalecube-js
      branch: master
