sudo: false
cache:
  yarn: true
  directories:
  - node_modules
language: node_js
node_js:
- '8'
before_install:
- echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > ~/.npmrc
install:
- yarn install
- yarn run bootstrap
- yarn run flow:install

script:
- yarn run build
- npm run test
- 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then yarn run deploy:canary; fi'

deploy:
  - provider: script
    skip_cleanup: true
    github-token: $GITHUB_TOKEN
    script: git checkout develop && yarn run deploy:prepublish
    on:
      repo: scalecube/scalecube-js
      branch: develop
      condition: '! $TRAVIS_COMMIT_MESSAGE =~ \[skip\ publish\]'
  - provider: script
    skip_cleanup: true
    script: yarn run deploy:publish
    on:
      repo: scalecube/scalecube-js
      branch: master

after_deploy:
  - git status
